spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crawler
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:/db/migration
